description: Checks the status of a kubernetes deployment and waits for all new pods to start and to report as healthy
parameters:
  maxAttempts:
    type: integer
    default: 30
  kubernetesNamespace:
    type: string
  kubernetesDeployment:
    type: string
steps:
  -
    run:
      name: Monitor Rollout
      command: |
        ATTEMPTS=0
        ROLLOUT_STATUS_CMD="kubectl rollout status deployment/<< parameters.kubernetesDeployment >> -n << parameters.kubernetesNamespace >>"
        until $ROLLOUT_STATUS_CMD || [ $ATTEMPTS -eq << parameters.maxAttempts >> ]; do
          $ROLLOUT_STATUS_CMD
          ATTEMPTS=$((attempts + 1))
          sleep 10
        done